import {
  Banknote,
  Bookmark,
  Camera,
  Cpu,
  CreditCard,
  Droplets,
  HeartPulse,
  Layers,
  LayoutGrid,
  Leaf,
  Package,
  PawPrint,
  PencilLine,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Sprout,
  Sun,
  Truck,
  Upload,
  User,
  Wifi,
  type LucideIcon,
} from "lucide-react";
import type { FaqIconKey } from "@/data/faqs";

export const FAQ_ICONS: Record<FaqIconKey, LucideIcon> = {
  banknote: Banknote,
  bookmark: Bookmark,
  camera: Camera,
  cpu: Cpu,
  "credit-card": CreditCard,
  droplets: Droplets,
  "heart-pulse": HeartPulse,
  layers: Layers,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  package: Package,
  "paw-print": PawPrint,
  "pencil-line": PencilLine,
  share: Share2,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  sprout: Sprout,
  sun: Sun,
  truck: Truck,
  upload: Upload,
  user: User,
  wifi: Wifi,
};
